/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "cec52f3dd4465dd7389298b97ab723856c556bd5"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
